# Generated by Django 2.1.1 on 2020-03-25 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Moh_Tracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(max_length=100)),
                ('tracker', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Nhandan_Title',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('page_link', models.URLField()),
                ('summary', models.TextField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='VnExpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('page_link', models.URLField()),
                ('summary', models.TextField()),
                ('img', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='WorldMeter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_infected', models.CharField(max_length=50)),
                ('total_death', models.CharField(max_length=50)),
                ('total_recovery', models.CharField(max_length=50)),
                ('new_infected', models.CharField(max_length=50)),
            ],
        ),
    ]
