# Generated by Django 2.1.1 on 2020-03-22 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VnExpress',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('news_title', models.CharField(max_length=255)),
                ('summary', models.TextField()),
                ('img', models.URLField()),
            ],
        ),
    ]
