# Generated by Django 2.1.1 on 2020-03-24 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('virus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='moh_number',
            name='moh_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moh_tracker',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='moh_tracker',
            name='tracker',
            field=models.TextField(),
        ),
    ]
